osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode10.1
        env: 
          - GCC_ON_MACOS=1
          - CONAN_GCC_VERSIONS=8
          - BREW_GCC="brew update && brew install --verbose gcc@8 && CC=gcc-8 && CXX=g++-8"
          
before_install:
  - if ! test -z $GCC_ON_MACOS; then echo "Installing GCC..." && eval ${BREW_GCC}; fi
  - cd /usr/bin
  - ln -s /usr/local/bin/gcc-8 cc
  - ln -s /usr/local/bin/gcc-8 gcc
  - ln -s /usr/local/bin/g++-8 c++
  - ln -s /usr/local/bin/g++-8 g++
  
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
