osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode10.1
        env: 
          - GCC_ON_MACOS=1
          - CONAN_GCC_VERSIONS=8
          - BREW_GCC="brew update && brew install --verbose gcc@8 && CC=gcc-8 && CXX=g++-8"
          - SET_GCC_ENV="cd /usr/local/bin && sudo ln -s gcc-8 cc && sudo ln -s g++-8 c++ && cd -"
          
before_install:
  - if ! test -z $GCC_ON_MACOS; then echo "Installing GCC..." && eval ${BREW_GCC}; fi
  - if ! test -z $GCC_ON_MACOS; then echo "Setting GCC as default..." && eval ${SET_GCC_ENV}; fi
  - gcc -v
  - g++ -v
  - cc -v
  - c++ -v
  
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
